F testCase/zzj/test_OrderInquiry.py::test_01_querySecOrder_正确报文获取最新的第二笔订单
 @allure.description("测试 /order/querySecOrder 接口用例")
! D:\python\lib\site-packages\_pytest\resultlog.py
 Traceback (most recent call last):
   File "D:\python\lib\site-packages\_pytest\main.py", line 205, in wrap_session
     session.exitstatus = doit(config, session) or 0
   File "D:\python\lib\site-packages\_pytest\main.py", line 249, in _main
     config.hook.pytest_runtestloop(session=session)
   File "D:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
     return self._hookexec(self, self.get_hookimpls(), kwargs)
   File "D:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
     return self._inner_hookexec(hook, methods, kwargs)
   File "D:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
   File "D:\python\lib\site-packages\pluggy\callers.py", line 208, in _multicall
     return outcome.get_result()
   File "D:\python\lib\site-packages\pluggy\callers.py", line 80, in get_result
     raise ex[1].with_traceback(ex[2])
   File "D:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
     res = hook_impl.function(*args)
   File "D:\python\lib\site-packages\_pytest\main.py", line 270, in pytest_runtestloop
     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
   File "D:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
     return self._hookexec(self, self.get_hookimpls(), kwargs)
   File "D:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
     return self._inner_hookexec(hook, methods, kwargs)
   File "D:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
   File "D:\python\lib\site-packages\pluggy\callers.py", line 208, in _multicall
     return outcome.get_result()
   File "D:\python\lib\site-packages\pluggy\callers.py", line 80, in get_result
     raise ex[1].with_traceback(ex[2])
   File "D:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
     res = hook_impl.function(*args)
   File "D:\python\lib\site-packages\_pytest\runner.py", line 77, in pytest_runtest_protocol
     runtestprotocol(item, nextitem=nextitem)
   File "D:\python\lib\site-packages\_pytest\runner.py", line 92, in runtestprotocol
     reports.append(call_and_report(item, "call", log))
   File "D:\python\lib\site-packages\_pytest\runner.py", line 176, in call_and_report
     hook.pytest_runtest_logreport(report=report)
   File "D:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
     return self._hookexec(self, self.get_hookimpls(), kwargs)
   File "D:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
     return self._inner_hookexec(hook, methods, kwargs)
   File "D:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
   File "D:\python\lib\site-packages\pluggy\callers.py", line 208, in _multicall
     return outcome.get_result()
   File "D:\python\lib\site-packages\pluggy\callers.py", line 80, in get_result
     raise ex[1].with_traceback(ex[2])
   File "D:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
     res = hook_impl.function(*args)
   File "D:\python\lib\site-packages\_pytest\resultlog.py", line 83, in pytest_runtest_logreport
     self.log_outcome(report, code, longrepr)
   File "D:\python\lib\site-packages\_pytest\resultlog.py", line 64, in log_outcome
     self.write_log_entry(testpath, lettercode, longrepr)
   File "D:\python\lib\site-packages\_pytest\resultlog.py", line 58, in write_log_entry
     print(" %s" % line, file=self.logfile)
 UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f447' in position 54: illegal multibyte sequence
